#!/usr/bin/env node
'use strict'

const App = require("."), args = process.argv.slice(2)
var arg
while (arg = args.shift()) {
    if (arg.startsWith("--")) {
        if (arg.startsWith("--working-directory=")) {
            App.setWD(arg.substring("--working-directory=".length))
            continue
        }
        else {
            console.log(`'Option ${arg}' is unrecognizable.`)
            break
        }
    }
    else if (arg.startsWith("-")) {
        if (arg === "-wd") {
            App.setWD(args.shift())
        }
        else {
            console.log(`'${arg}' is not a phloemjs option.`)
            break
        }
        continue
    }

    if (arg === "init") {
        App.init()
        break
    }
    else if (arg === "setup") {
        App.setup()
        break
    }
    else if (arg === "run") {
        if ((arg = args.shift()) === "-p") App.setPort(args.shift())
        App.run()
        break
    }
    else if (arg === "build") {
        if ((arg = args.shift()) === "-p") App.setPort(args.shift())
        App.run()
        break
    }
    else {
        console.log(`'${arg}' is not a phloemjs command.`)
        break
    }
}
